image: Visual Studio 2019
version: '{build}'
branches:
  only:
  - master
skip_tags: true
configuration: Release (Ruby 2.6)
platform:
- x64
- x86
clone_depth: 3
environment:
  DEBUG: true
test_script:
- ps: >-
    If ($env:PLATFORM -Eq "x64") {
      $env:PATH = "C:\Ruby26-x64\bin;$env:PATH"
    }
    Else {
      $env:PATH = "C:\Ruby26\bin;$env:PATH"
    }
    
    gem install rake rake-compiler minitest --no-doc
    
    cmd /c rake format test TEST=test/test_window.rb TESTOPTS='-v' '2>&1'
